default_language_version:
    python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  -   repo: https://github.com/aws-cloudformation/cfn-lint
      rev: v1.14.0
      hooks:
      -   id: cfn-lint
          files: .*(cfn|cloudformation).*\.(json|yml|yaml)$
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.28
    hooks:
      # Update the uv lockfile
      - id: uv-lock
